server:
  port: 8126
  servlet:
    context-path: /api
spring:
  application:
    name: zzx-ai-agent
  profiles:
    active: pro
  datasource:
    # MySql
    one:
      username: ${ai-agent.spring.datasource.one.username}
      password: ${ai-agent.spring.datasource.one.password}
      jdbc-url: jdbc:mysql://${ai-agent.spring.datasource.one.host}:${ai-agent.spring.datasource.one.port}/${ai-agent.spring.datasource.one.databases}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
    # PGVector
    two:
      jdbc-url: jdbc:postgresql://pgm-bp1plb4o54qd8dx0so.pg.rds.aliyuncs.com:5432/zzx_ai_agent
      username: ${ai-agent.spring.datasource.two.username}
      password: ${ai-agent.spring.datasource.two.password}

  ai:
    dashscope:
      api-key: "${ai-agent.spring.ai.dashscope.api-key}"
      chat:
        options:
          model: "${ai-agent.spring.ai.dashscope.chat-model}"
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
#    mcp:
#      client:
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8127


  # 用于邮件发送 此处使用QQ邮箱
  mail:
    username: zhaozhixuan513@foxmail.com        # 你自己的邮箱
    password: tmkaszmchrwubahf                  # 授权码
    host: smtp.qq.com                           # QQ SMTP 服务器
    from: zhaozhixuan513@foxmail.com            # 你自己的邮箱
    port: 465                                   # 添加端口配置 465/587 均可
    properties:
      mail:
        smtp:
          ssl:
            enable: true  # 启用SSL
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zzx.zzxaiagent.entity.po


# springdoc-openapi 接口文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zzx.zzxaiagent.controller

# knife4j 的增强配置，不需要可以去掉
knife4j:
  enable: true
  setting:
    language: zh_cn

# 用于百度翻译
baidu:
  api-key: "${ai-agent.baidu.api-key}"
  security-key: "${ai-agent.baidu.security-key}"

# 用于GitHub搜索
github:
  token: "${ai-agent.github.token}"

# 谷歌搜索需要开启代理服务
google:
  api-key: "${ai-agent.google.api-key}"
  search-engine-id: "${google.search-engine-id}"

#  用于百度搜索 https://www.searchapi.io/
searchapi:
  api-key: "${ai-agent.searchapi.api-key}"

# 阿里云 OSS 存储服务
aliyvn:
  alioss:
    endpoint: "${ai-agent.aliyvn.alioss.endpoint}"
    access-key-id: "${ai-agent.aliyvn.alioss.access-key-id}"
    access-key-secret: "${ai-agent.aliyvn.alioss.access-key-secret}"
    bucket-name: "${ai-agent.aliyvn.alioss.bucket-name}"